spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 6748013e4aece7bdf395
            clientSecret: dad0a22dd9ed0da30454adff893f09ef46d1aaf4

logging:
  level:
    org:
      springframework:
        web: DEBUG